#cloud-config
users:
  - name: dave
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, docker
    shell: /usr/bin/zsh
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxyz...yourkeyhere...
    lock_passwd: true
package_update: true
package_upgrade: true
packages:
  - apache2-utils
  - build-essential
  - ca-certificates
  - clang
  - cmake
  - curl
  - direnv
  - dnsutils
  - docker.io
  - fd-find
  - gdb
  - git
  - gnupg
  - gnupg2
  - htop
  - hugo
  - ipcalc
  - jq
  - less
  - libclang-dev
  - liblzma-dev
  - libpq-dev
  - libprotoc-dev
  - libsqlite3-dev
  - libssl-dev
  - libvirt-clients
  - libvirt-daemon-system
  - lldb
  - locales
  - man
  - mosh
  - mtr-tiny
  - musl-tools
  - ncdu
  - netcat-openbsd
  - openssh-server
  - pkg-config
  - protobuf-compiler
  - pwgen
  - python
  - python3
  - python3-flake8
  - python3-pip
  - python3-setuptools
  - python3-venv
  - python3-wheel
  - qemu-kvm
  - qrencode
  - quilt
  - ripgrep
  - shellcheck
  - socat
  - software-properties-common
  - sqlite3
  - stow
  - sudo
  - tig
  - tmate
  - tmux
  - tree
  - unzip
  - wget
  - zgen
  - zip
  - zlib1g-dev
  - zsh
write_files:
  - path: /etc/motd
    content: |
      Welcome to your server, Dave!
runcmd:
  - ["usermod", "-s", "/usr/bin/zsh", "dave"]
  - curl -o /root/bootstrap.sh https://example.com/path/to/bootstrap.sh
  - chmod +x /root/bootstrap.sh
  - /root/bootstrap.sh
